# Generated by Django 3.2 on 2021-09-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='sdob',
            field=models.DateField(null=True),
        ),
    ]
