# Generated by Django 3.2 on 2021-09-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagro', '0003_auto_20210925_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
