# Generated by Django 3.2 on 2021-09-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eagro', '0004_alter_signupuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
