# Generated by Django 3.2 on 2021-09-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagro', '0005_signupuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='signupuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
